### PR TITLE
Prepare release 1.6.1

### PR DESCRIPTION
**Pull request by razman786**
Tigger version 1.6.1 with support for Ubuntu 22.04:

Proposed steps:

1. Process PR 37 for tigger-lsm first (https://github.com/ratt-ru/tigger-lsm/pull/37). PR 37 for tigger-lsm already includes a refined PR 36 (https://github.com/ratt-ru/tigger-lsm/pull/36) for convenience. This is what the newer features and testing of Tigger v1.6.1 has been worked upon. 
2. Please note I've not looked into or tested PR 34 for tigger-lsm (https://github.com/ratt-ru/tigger-lsm/pull/34)
4. Currently the `setup.py` of Tigger v1.6.1 expects PR 37 (at minimum) to form tigger-lsm v1.7.1 for processing mosaic and FITS files with header issues. Therefore release v1.7.2 or use tigger-lsm PR 37 for this PR.
6. Process PR #132 .
7. Process this PR for Tigger v1.6.1

N.B. you can test ARM64 Ubuntu 22.04 via qemu on x86 - it's slow and painful but does work, eventually.

EDIT: Fixed typo 

Changes:
* Supports Ubuntu 22.04
* Beta support for Ubuntu 22.04 ARM64 (with PyQwt deb pkg) - it should allow a Mac M1 user to use Ubuntu 22.04 for ARM64 with UTM virtualisation on Mac OS X
* Dependent on the latest tigger-lsm (i.e. PR 37) 
* Fixed live profile selection when using mosaic images (and tigger-lsm PR 37)
* Fixed float errors with updated library API's
* Re-enabled splash screen
* Fixes venv pip3 bug
* Updated URL's
* GitHub Actions are now compatible with 'act' for running locally
* Actions now test VENV installations on Ubuntu 20.04 and 22.04
* Improved Action tests and logging
* Failed Actions are processed by an error reporting step
* Copyright notice years updated and redundant UTF-8 file declarations removed
* Code was checked for consistency with v1.5.1 as part of #129 and PR #132
* Image zooming refined (trackpad and  mouse)
* Dockable widget handling improved, window and image sizes should remain better
* Minor file formatting
* Updated README.rst
* Updated CHANGELOG.rst

# #

### CODE REVIEW

**Comment by razman786** [comment]
As a note, the failing tests above are not due to Tigger, but the Actions VM's failing for 18.04 and 22.04 when downloading and installing deb packages via apt. Tests pass locally using 'act' as was the case with 20.04 above.

**Comment by bennahugo** [comment]
Trying to load in an image with the menu I run across:
```
Welcome to Tigger 1.6.1
Please wait a second while the GUI starts up.
Detected screen size 1200x1920, usable area 1200x1890
Traceback (most recent call last):
  File "/home/hugo/workspace/tigger/TigGUI/Images/Manager.py", line 161, in loadImage
    layout.addWidget(_flabel, 0, 3)
AttributeError: 'NoneType' object has no attribute 'addWidget'
```

**Comment by razman786** [comment]
> Trying to load in an image with the menu I run across:
> 
> ```
> Welcome to Tigger 1.6.1
> Please wait a second while the GUI starts up.
> Detected screen size 1200x1920, usable area 1200x1890
> Traceback (most recent call last):
>   File "/home/hugo/workspace/tigger/TigGUI/Images/Manager.py", line 161, in loadImage
>     layout.addWidget(_flabel, 0, 3)
> AttributeError: 'NoneType' object has no attribute 'addWidget'
> ```
> 
> It does not happen when you load in images using the command line

I cannot replicate it. What version of Ubuntu are you testing with?

**Comment by bennahugo** [comment]
Running Ubuntu 18.04 with my previous testing environment

**Comment by razman786** [comment]
Ah ok that explains it. My Ubuntu 18.04 setup passed away along with the laptop it was on :( But I was able to replicate the issue. It seems that some Ubuntu's use the native file dialog by default and others don't... Give the latest commit a spin, it should work, and if the widget layout cannot be customised it will not show the preview pane.

**Review by bennahugo — APPROVED** [review]

**Comment by bennahugo** [comment]
Ok thanks @razman786 I've run through it for a bit and I can't see anything majorly amiss. I will accept and merge this one!

**Pull request merged**
