### PR TITLE
Closes issue #128 - FITS headers after arithmetic operations

### LINKED ISSUE #128: Saved FITS images from arithmetic operations have bad headers
Saving the result of an image arithmetic operation seems to output only a 2D data array in the FITS header. You can see here on the left the header of an input file, and on the right the header of Tigger's output. Note the `NAXIS = 2` entry on the right, as well as missing dimensions for `NAXIS3` and `NAXIS4`.

Screen Shot 2021-10-12 at 10 25 10

### PR DESCRIPTION
**Pull request by razman786**
Closes #128 

FITS headers are now corrected and reconstructed correctly after arithmetic operations.

### CODE REVIEW

**Comment by razman786** [comment]
Might want to squash and merge this one...

**Comment by bennahugo** [comment]
ok to test

**Review by bennahugo — APPROVED** [review]
I don't see any issues with this if this is solely stemming from trimming off 1 element dimensions. The only problem can come in from a reduce operation on a dimension in the middle of the cube e.g. a.sum(axis=x) where 0 < x < a.ndim

**Comment by bennahugo** [comment]
retest this please

**Pull request merged**
